interface ChatWeb3QuestionsRefactored {
  [key: string]: { original: string; reformatted: string }[];
}

export const chatWeb3QuestionsRefactored: ChatWeb3QuestionsRefactored = {
  'opensea.io': [
    { original: 'What is Opensea?', reformatted: 'Can you explain to me what Opensea is?' },
    { original: 'How to list an NFT?', reformatted: 'How can I list an item on opensea?' },
    { original: 'What are gas fees?', reformatted: 'What are gas gees on opensea?' },
    { original: 'What is NFT rarity?', reformatted: 'What is NFT rarity on opensea?' },
  ],
  'galxe.com': [
    { original: 'What is Galxe?', reformatted: 'Could you tell me more about Galxe on galxe.com?' },
    { original: 'How to make a trade?', reformatted: 'How can I trade on galxe.com?' },
    { original: 'Supported chains?', reformatted: 'What chains does galxe.com support?' },
    { original: 'What are Galxe tokens?', reformatted: 'What are the Galxe tokens on galxe.com?' },
  ],
  'gitcoin.co': [
    { original: 'What is Gitcoin?', reformatted: 'Can you tell me what Gitcoin is on gitcoin.co?' },
    { original: 'How to fund a project?', reformatted: 'How can I fund a project on gitcoin.co?' },
    { original: 'How to start a grant?', reformatted: 'How can I start a grant on gitcoin.co?' },
    {
      original: 'Gitcoin hackathons?',
      reformatted: 'How can I participate in a Gitcoin hackathon on gitcoin.co?',
    },
  ],
  'uniswap.org': [
    { original: 'What is Uniswap?', reformatted: 'Can you explain what Uniswap is on uniswap.org?' },
    { original: 'How to swap tokens?', reformatted: 'How can I swap tokens on uniswap.org?' },
    { original: 'How to adjust slippage?', reformatted: 'How can I adjust slippage on uniswap.org?' },
    { original: 'How to add liquidity?', reformatted: 'How can I add liquidity on Uniswap via uniswap.org?' },
  ],
  'blur.io': [
    { original: 'What is Blur?', reformatted: 'Can you tell me what Blur is?' },
    { original: 'How to list an NFT?', reformatted: 'How can I list an NFT on blur.io?' },
    { original: 'What are gas fees?', reformatted: 'What are gas fees on blur.io?' },
    { original: 'What is NFT rarity?', reformatted: 'What is NFT rarity on blur.io?' },
  ],
  'snapshot.org': [
    { original: 'What is Snapshot?', reformatted: 'Could you explain what Snapshot is on snapshot.org?' },
    { original: 'Vote how?', reformatted: 'How can I vote on snapshot.org?' },
    { original: 'Propose vote?', reformatted: 'How can I propose a vote on snapshot.org?' },
    { original: "Snapshot's role?", reformatted: 'What is the role of Snapshot on snapshot.org?' },
  ],
  'mint.fun': [
    { original: 'What is Mint.fun?', reformatted: 'Could you tell me more about Mint on mint.fun?' },
    { original: 'How do i earn rewards?', reformatted: 'How can I earn rewards on mint.fun?' },
    { original: 'How to play games?', reformatted: 'How can I play games on mint.fun?' },
    { original: "What are Mint's features?", reformatted: 'What are the features of Mint on mint.fun?' },
  ],
  'holograph.xyz': [
    { original: 'What is Holograph?', reformatted: 'Could you tell me more about Holograph on holograph.xyz?' },
    { original: 'How do I use it?', reformatted: 'How can I use Holograph on holograph.xyz?' },
    { original: 'What is Explore 3D?', reformatted: 'How can I explore in 3D on holograph.xyz?' },
    { original: 'Holograph applications?', reformatted: 'What are the applications of Holograph on holograph.xyz?' },
  ],
  'guild.xyz': [
    { original: 'What is Guild.xyz?', reformatted: 'Could you explain what Guild is on guild.xyz?' },
    { original: 'How do I join?', reformatted: 'How can I join Guild on guild.xyz?' },
    { original: 'How do I contribute?', reformatted: 'How can I contribute to Guild on guild.xyz?' },
    { original: "What are Guild's benefits?", reformatted: 'What are the benefits of joining Guild on guild.xyz?' },
  ],
  'zigzag.exchange': [
    { original: 'What is Zigzag?', reformatted: 'Can you explain what Zigzag is on zigzag.exchange?' },
    { original: 'How do I exchange?', reformatted: 'How can I exchange currencies on zigzag.exchange?' },
    { original: 'How do i deposit?', reformatted: 'How can I make a deposit on zigzag.exchange?' },
    { original: "What are Zigzag's features?", reformatted: 'What features does Zigzag offer on zigzag.exchange?' },
  ],
  'orbiter.finance': [
    { original: 'What is Orbiter?', reformatted: 'Could you tell me what Orbiter is on orbiter.finance?' },
    { original: 'How do I invest?', reformatted: 'How can I invest on orbiter.finance?' },
    { original: 'How do I Withdraw?', reformatted: 'How can I make a withdrawal on orbiter.finance?' },
    { original: "Orbiter's products?", reformatted: 'What products does Orbiter offer on orbiter.finance?' },
  ],
  'lenster.xyz': [
    { original: 'What is Lenster?', reformatted: 'Can you tell me what Lenster is on lenster.xyz?' },
    { original: 'Start creating?', reformatted: 'How can I start creating on lenster.xyz?' },
    { original: 'How do I view content?', reformatted: 'How can I view content on lenster.xyz?' },
    { original: 'Lenster features?', reformatted: 'What are the features of Lenster on lenster.xyz?' },
  ],
  'zkbridge.com': [
    { original: 'What is ZKBridge?', reformatted: 'Could you explain what ZKBridge is on zkbridge.com?' },
    { original: 'How do I connect wallet?', reformatted: 'How can I connect my wallet on zkbridge.com?' },
    { original: 'How do I transfer assets?', reformatted: 'How can I transfer assets on zkbridge.com?' },
    { original: 'ZKBridge purpose?', reformatted: 'What is the purpose of ZKBridge on zkbridge.com?' },
  ],
  'revoke.cash': [
    { original: 'What is Revoke.cash?', reformatted: 'Can you tell me what Revoke is on revoke.cash?' },
    { original: 'How do I start?', reformatted: 'How can I get started with Revoke on revoke.cash?' },
    { original: 'Manage permissions?', reformatted: 'How can I manage permissions on revoke.cash?' },
    { original: 'When to Revoke?', reformatted: 'How often should I use revoke.cash to manage my permissions?' },
  ],
  'defillama.com': [
    { original: 'What is DeFiLlama?', reformatted: 'Could you tell me what DeFiLlama is on defillama.com?' },
    { original: 'Analyze data?', reformatted: 'How can I analyze data on defillama.com?' },
    { original: 'View rankings?', reformatted: 'How can I view rankings on defillama.com?' },
    { original: 'DeFiLlama purpose?', reformatted: 'What is the purpose of DeFiLlama on defillama.com?' },
  ],
  'zksync.io': [
    { original: 'What is ZkSync?', reformatted: 'Can you explain what ZkSync is on zksync.io?' },
    { original: 'Transact how?', reformatted: 'How can I transact on zksync.io?' },
    { original: 'Withdraw how?', reformatted: 'How can I make a withdrawal on zksync.io?' },
    { original: 'ZkSync benefits?', reformatted: 'What are the benefits of ZkSync on zksync.io?' },
  ],
  'debank.com': [
    { original: 'What is DeBank?', reformatted: 'Could you tell me more about DeBank on debank.com?' },
    { original: 'Connect wallet?', reformatted: 'How can I connect my wallet on debank.com?' },
    { original: 'Analyze portfolio?', reformatted: 'How can I analyze my portfolio on debank.com?' },
    { original: 'DeBank services?', reformatted: 'What services does DeBank offer on debank.com?' },
  ],
  'rarity.game': [
    { original: 'What is Rarity?', reformatted: 'Can you explain what Rarity is on rarity.game?' },
    { original: 'Start playing?', reformatted: 'How can I start playing on rarity.game?' },
    { original: 'Progress game?', reformatted: 'How can I progress in the game on rarity.game?' },
    { original: 'NFTs role?', reformatted: 'What role do NFTs play on rarity.game?' },
  ],
  'cometh.io': [
    { original: 'What is Cometh?', reformatted: 'Could you explain what Cometh is on cometh.io?' },
    { original: 'Start playing?', reformatted: 'How can I start playing on cometh.io?' },
    { original: 'Earn rewards?', reformatted: 'How can I earn rewards on cometh.io?' },
    { original: 'Blockchain role?', reformatted: 'What role does the blockchain play on cometh.io?' },
  ],
  'aave.com': [
    { original: 'What is Aave?', reformatted: 'Could you tell me what Aave is on aave.com?' },
    { original: 'How do I lend on Aave?', reformatted: 'How can I lend on aave.com?' },
    { original: 'How do I barrow?', reformatted: 'How can I borrow on aave.com?' },
    { original: "What are Aave's services?", reformatted: 'What services does Aave provide on aave.com?' },
  ],
  'metamask.io': [
    { original: 'How is Metamask?', reformatted: 'What is Metamask?' },
    { original: 'Transfer assets?', reformatted: 'How can I transfer assets on metamask.io?' },
    { original: 'Gas fees?', reformatted: 'What are the gas fees on metamask.io?' },
    { original: 'Private key?', reformatted: 'How can I manage my private key on metamask.io?' },
  ],
  'coinbase.com': [
    { original: 'What is Coinbase?', reformatted: 'What is Coinbase?' },
    { original: 'Sell crypto?', reformatted: 'How can I sell crypto on coinbase.com?' },
    { original: 'Transfer assets?', reformatted: 'How can I transfer assets on coinbase.com?' },
    { original: 'Security measures?', reformatted: 'What security measures does coinbase.com have in place?' },
  ],
  'trustwallet.com': [
    { original: 'What is Trust Wallet?', reformatted: 'What is Trust Wallet?' },
    { original: 'Buy tokens?', reformatted: 'How can I buy tokens on trustwallet.com?' },
    { original: 'Staking options?', reformatted: 'What are the staking options on trustwallet.com?' },
    { original: 'DApps access?', reformatted: 'How can I access DApps on trustwallet.com?' },
  ],
  'zerion.io': [
    { original: 'What is Zerion?', reformatted: 'What is Zerion Wallet?' },
    { original: 'Buy assets?', reformatted: 'How can I buy assets on zerion.io?' },
    { original: 'Manage DeFi?', reformatted: 'How can I manage DeFi on zerion.io?' },
    { original: 'Transaction history?', reformatted: 'How can I see my transaction history on zerion.io?' },
  ],
  'zengo.com': [
    { original: 'What is Zengo?', reformatted: 'What is Zengo Wallet?' },
    { original: 'Buy crypto?', reformatted: 'How can I buy crypto on zengo.com?' },
    { original: 'Sell crypto?', reformatted: 'How can I sell crypto on zengo.com?' },
    { original: 'Secure backup?', reformatted: 'How can I securely backup my wallet on zengo.com?' },
  ],
  'argent.xyz': [
    { original: 'Mobile DeFi?', reformatted: 'What does Mobile DeFi mean on www.argent.xyz?' },
    { original: 'How to send?', reformatted: 'How can I send assets on www.argent.xyz?' },
    { original: 'Manage assets?', reformatted: 'How can I manage my assets on www.argent.xyz?' },
    { original: 'Secure wallet?', reformatted: 'How secure is the wallet on www.argent.xyz?' },
  ],
  'rainbow.me': [
    { original: 'What is rainbow?', reformatted: 'What is rainbow on rainbow.me?' },
    { original: 'Buy tokens?', reformatted: 'How can I buy tokens on rainbow.me?' },
    { original: 'Wallet connect?', reformatted: 'How can I connect my wallet on rainbow.me?' },
    { original: 'Safe backup?', reformatted: 'How can I safely backup my data on rainbow.me?' },
  ],
  'trezor.io': [
    { original: 'What is Trezor', reformatted: 'What is trezor on trezor.io?' },
    { original: 'Backup recovery?', reformatted: 'How does backup recovery work on trezor.io?' },
    { original: 'Send crypto?', reformatted: 'How can I send crypto on trezor.io?' },
    { original: 'Security features?', reformatted: 'What security features does trezor.io provide?' },
  ],
  'ledger.com': [
    { original: 'What is Ledger?', reformatted: 'What is ledger on ledger.com?' },
    { original: 'Send assets?', reformatted: 'How can I send assets on ledger.com?' },
    { original: 'Update firmware?', reformatted: 'How can I update the firmware on ledger.com?' },
    { original: 'Backup seed?', reformatted: 'How can I backup my seed on ledger.com?' },
  ],
  'exodus.com': [
    { original: 'What is Exodus?', reformatted: 'What is exodus on exodus.com?' },
    { original: 'Manage assets?', reformatted: 'How can I manage my assets on exodus.com?' },
    { original: 'Secure backup?', reformatted: 'How can I securely backup my data on exodus.com?' },
    { original: 'Swap assets?', reformatted: 'How can I swap assets on exodus.com?' },
  ],
  'phantom.app': [
    { original: 'What is Phantom?', reformatted: 'What is Phantom the web3 wallet?' },
    { original: 'Stake SOL?', reformatted: 'How can I stake SOL on phantom.app?' },
    { original: 'NFT support?', reformatted: 'Does phantom.app support NFTs?' },
    { original: 'Swap tokens?', reformatted: 'How can I swap tokens on phantom.app?' },
  ],
  '1inch.io': [
    { original: 'What is 1inch?', reformatted: 'Could you explain what 1inch is on 1inch.io?' },
    { original: 'Swap tokens?', reformatted: 'How can I swap tokens on 1inch.io?' },
    { original: 'Trading features?', reformatted: 'What trading features does 1inch.io provide?' },
    { original: '1inch services?', reformatted: 'What services does 1inch.io offer?' },
  ],
  'binance.com': [
    { original: 'What is Binance?', reformatted: 'What is binance on binance.com?' },
    { original: 'Buy assets?', reformatted: 'How can I buy assets on binance.com?' },
    { original: 'Sell assets?', reformatted: 'How can I sell assets on binance.com?' },
    { original: 'Binance security?', reformatted: 'What security measures does binance.com have in place?' },
  ],
  'collab.land': [
    { original: 'What is Collab?', reformatted: 'Could you explain what Collab is on collab.land?' },
    { original: 'Join community?', reformatted: 'How can I join the community on collab.land?' },
    { original: 'Token roles?', reformatted: 'What roles do tokens play on collab.land?' },
    { original: 'Use Collab?', reformatted: 'How can I use Collab on collab.land?' },
  ],
  'mirror.world': [
    { original: 'What is Mirror?', reformatted: 'Could you explain what Mirror is on mirror.world?' },
    { original: 'Develop Dapp?', reformatted: 'How can I develop a Dapp on mirror.world?' },
    { original: 'Monetize how?', reformatted: 'How can I monetize on mirror.world?' },
    { original: 'Mirror services?', reformatted: 'What services does mirror.world offer?' },
  ],
  'slingshot.finance': [
    { original: 'What is Slingshot?', reformatted: 'Could you explain what Slingshot is on slingshot.finance?' },
    { original: 'Swap tokens?', reformatted: 'How can I swap tokens on slingshot.finance?' },
    { original: '0% fees?', reformatted: 'Does slingshot.finance offer 0% fees?' },
    { original: 'Slingshot use?', reformatted: 'How can I use Slingshot on slingshot.finance?' },
  ],
  'zapper.fi': [
    { original: 'What is Zapper?', reformatted: 'Could you explain what Zapper is on zapper.fi?' },
    { original: 'Explore DeFi?', reformatted: 'How can I explore DeFi on zapper.fi?' },
    { original: 'Discover NFTs?', reformatted: 'How can I discover NFTs on zapper.fi?' },
    { original: 'Zapper DAOs?', reformatted: 'What role do DAOs play on zapper.fi?' },
  ],
  'alchemy.com': [
    { original: 'What is Alchemy?', reformatted: 'Could you explain what Alchemy is on alchemy.com?' },
    { original: 'Learn Ethereum?', reformatted: 'Where can I learn about Ethereum on alchemy.com?' },
    { original: 'Solidity bootcamp?', reformatted: 'Does alchemy.com offer a Solidity bootcamp?' },
    { original: 'Alchemy services?', reformatted: 'What services does alchemy.com offer?' },
  ],
  'arbitrum.io': [
    { original: 'What is Arbitrum?', reformatted: 'Could you explain what Arbitrum is on arbitrum.io?' },
    { original: 'Build Dapps?', reformatted: 'How can I build Dapps on arbitrum.io?' },
    { original: 'Ethereum layer2?', reformatted: 'Does arbitrum.io provide an Ethereum Layer 2 solution?' },
    { original: 'Arbitrum benefits?', reformatted: 'What are the benefits of using arbitrum.io?' },
  ],
  'bnbchain.com': [
    { original: 'What is BNBChain?', reformatted: 'Could you explain what BNBChain is on bnbchain.com?' },
    { original: 'Transaction volume?', reformatted: 'What is the transaction volume on bnbchain.com?' },
    { original: 'Daily users?', reformatted: 'How many daily users are there on bnbchain.com?' },
    { original: 'Use BNBChain?', reformatted: 'How can I use BNBChain on bnbchain.com?' },
  ],
  'ethereum.org': [
    { original: 'What is Ethereum?', reformatted: 'Could you explain what Ethereum is on ethereum.org?' },
    { original: 'Use Ethereum?', reformatted: 'How can I use Ethereum on ethereum.org?' },
    { original: 'Build Dapps?', reformatted: 'How can I build Dapps on ethereum.org?' },
    { original: 'Ethereum services?', reformatted: 'What services does ethereum.org provide?' },
  ],
  'layer3.xyz': [
    { original: 'What is Layer3?', reformatted: 'Could you explain what Layer3 is on layer3.xyz?' },
    { original: 'Learn web3?', reformatted: 'Where can I learn about web3 on layer3.xyz?' },
    { original: 'Community platform?', reformatted: 'Does layer3.xyz serve as a community platform?' },
    { original: 'Layer3 use?', reformatted: 'How can I use Layer3 on layer3.xyz?' },
  ],
  'optimism.io': [
    { original: 'What is Optimism?', reformatted: 'Could you explain what Optimism is on optimism.io?' },
    { original: 'Low-cost?', reformatted: 'Does optimism.io provide low-cost transactions?' },
    { original: 'Fast transactions?', reformatted: 'Does optimism.io provide fast transactions?' },
    { original: 'Use Optimism?', reformatted: 'How can I use Optimism on optimism.io?' },
  ],
  'polygon.technology': [
    { original: 'What is Polygon?', reformatted: 'Could you explain what Polygon is on polygon.technology?' },
    { original: 'Low fees?', reformatted: 'Does polygon.technology offer low transaction fees?' },
    { original: 'Fast transactions?', reformatted: 'Does polygon.technology offer fast transactions?' },
    { original: 'Use Polygon?', reformatted: 'How can I use Polygon on polygon.technology?' },
  ],
  'ens.domains': [
    { original: 'What is ENS?', reformatted: 'Could you explain what ENS is on ens.domains?' },
    { original: 'Decentralized usernames?', reformatted: 'Does ens.domains provide decentralized usernames?' },
    { original: 'ENS roles?', reformatted: 'What roles does ENS play on ens.domains?' },
    { original: 'Use ENS?', reformatted: 'How can I use ENS on ens.domains?' },
  ],
  'withtally.com': [
    { original: 'What is Tally?', reformatted: 'Could you explain what Tally is on withtally.com?' },
    { original: 'Govern DAO?', reformatted: 'How can I govern a DAO on withtally.com?' },
    { original: 'Use Tally?', reformatted: 'How can I use Tally on withtally.com?' },
    { original: 'Tally benefits?', reformatted: 'What are the benefits of using Tally on withtally.com?' },
  ],
  'mirror.xyz': [
    { original: 'What is Mirror?', reformatted: 'Could you explain what Mirror is on mirror.xyz?' },
    { original: 'Publish content?', reformatted: 'How can I publish content on mirror.xyz?' },
    { original: 'Use Mirror?', reformatted: 'How can I use Mirror on mirror.xyz?' },
    { original: 'Mirror services?', reformatted: 'What services does mirror.xyz offer?' },
  ],
  'sandbox.game': [
    { original: 'What is The Sandbox?', reformatted: 'Could you explain what The Sandbox is on sandbox.game?' },
    { original: 'Play game?', reformatted: 'How can I play the game on sandbox.game?' },
    { original: 'Create NFTs?', reformatted: 'How can I create NFTs on sandbox.game?' },
    { original: 'Monetize NFTs?', reformatted: 'How can I monetize NFTs on sandbox.game?' },
  ],
};
