interface ChatWeb3Questions {
  [key: string]: string[];
}

export const chatWeb3Questions: ChatWeb3Questions = {
  'opensea.io': ['NFT meaning?', 'Bid how?', 'Sell how?', 'Verify ownership?'],
  'galxe.com': ["What's Galxe?", 'Trade how?', 'Invest how?', 'Galxe tokens?'],
  'gitcoin.co': ["What's Gitcoin?", 'Fund project?', 'Start grant?', 'Gitcoin hackathon?'],
  'uniswap.org': ["What's Uniswap?", 'Swap tokens?', 'Add liquidity?', 'Stake Uniswap?'],
  'stargate.finance': ["What's Stargate?", 'Deposit how?', 'Withdraw how?', 'Supported cryptocurrencies?'],
  'blur.io': ["What's Blur?", 'Create blur?', 'Share creation?', 'Blur application?'],
  'snapshot.org': ["What's Snapshot?", 'Vote how?', 'Propose vote?', "Snapshot's role?"],
  'mint.fun': ["What's Mint?", 'Play games?', 'Earn rewards?', 'Mint features?'],
  'holograph.xyz': ["What's Holograph?", 'Use it?', 'Explore 3D?', 'Holograph applications?'],
  'guild.xyz': ["What's Guild?", 'Join how?', 'Contribute how?', 'Guild benefits?'],
  'zigzag.exchange': ["What's Zigzag?", 'Exchange how?', 'Deposit how?', 'Zigzag features?'],
  'orbiter.finance': ["What's Orbiter?", 'Invest how?', 'Withdraw how?', 'Orbiter products?'],
  'lenster.xyz': ["What's Lenster?", 'Start creating?', 'View content?', 'Lenster features?'],
  'zkbridge.com': ["What's ZKBridge?", 'Connect wallet?', 'Transfer assets?', 'ZKBridge purpose?'],
  'revoke.cash': ["What's Revoke?", 'Start how?', 'Manage permissions?', 'Use Revoke?'],
  'defillama.com': ["What's DeFiLlama?", 'Analyze data?', 'View rankings?', 'DeFiLlama purpose?'],
  'zksync.io': ["What's ZkSync?", 'Transact how?', 'Withdraw how?', 'ZkSync benefits?'],
  'debank.com': ["What's DeBank?", 'Connect wallet?', 'Analyze portfolio?', 'DeBank services?'],
  'rarity.game': ["What's Rarity?", 'Start playing?', 'Progress game?', 'NFTs role?'],
  'cometh.io': ["What's Cometh?", 'Start playing?', 'Earn rewards?', 'Blockchain role?'],
  'aave.com': ["What's Aave?", 'Lend how?', 'Borrow how?', 'Aave services?'],
  'metamask.io': ['How to connect?', 'Transfer assets?', 'Gas fees?', 'Private key?'],
  'coinbase.com': ['Buy crypto?', 'Sell crypto?', 'Transfer assets?', 'Security measures?'],
  'trustwallet.com': ['Manage assets?', 'Buy tokens?', 'Staking options?', 'DApps access?'],
  'zerion.io': ['Track portfolio?', 'Buy assets?', 'Manage DeFi?', 'Transaction history?'],
  'zengo.com/': ['Keyless wallet?', 'Buy crypto?', 'Sell crypto?', 'Secure backup?'],
  'www.argent.xyz': ['Mobile DeFi?', 'How to send?', 'Manage assets?', 'Secure wallet?'],
  'rainbow.me': ['NFT storage?', 'Buy tokens?', 'Wallet connect?', 'Safe backup?'],
  'trezor.io': ['Setup process?', 'Backup recovery?', 'Send crypto?', 'Security features?'],
  'ledger.com': ['Setup process?', 'Send assets?', 'Update firmware?', 'Backup seed?'],
  'exodus.com': ['Desktop wallet?', 'Manage assets?', 'Secure backup?', 'Swap assets?'],
  'phantom.app': ['Solana wallet?', 'Stake SOL?', 'NFT support?', 'Swap tokens?'],
  '1inch.io': ["What's 1inch?", 'Swap tokens?', 'Trading features?', '1inch services?'],
  'binance.com': ['Trade crypto?', 'Buy assets?', 'Sell assets?', 'Binance security?'],
  'collab.land': ["What's Collab?", 'Join community?', 'Token roles?', 'Use Collab?'],
  'mirror.world': ["What's Mirror?", 'Develop Dapp?', 'Monetize how?', 'Mirror services?'],
  'slingshot.finance': ["What's Slingshot?", 'Swap tokens?', '0% fees?', 'Slingshot use?'],
  'zapper.fi': ["What's Zapper?", 'Explore DeFi?', 'Discover NFTs?', 'Zapper DAOs?'],
  'alchemy.com': ["What's Alchemy?", 'Learn Ethereum?', 'Solidity bootcamp?', 'Alchemy services?'],
  'arbitrum.io': ["What's Arbitrum?", 'Build Dapps?', 'Ethereum layer2?', 'Arbitrum benefits?'],
  'bnbchain.com': ["What's BNBChain?", 'Transaction volume?', 'Daily users?', 'Use BNBChain?'],
  'ethereum.org': ["What's Ethereum?", 'Use Ethereum?', 'Build Dapps?', 'Ethereum services?'],
  'layer3.xyz': ["What's Layer3?", 'Learn web3?', 'Community platform?', 'Layer3 use?'],
  'optimism.io': ["What's Optimism?", 'Low-cost?', 'Fast transactions?', 'Use Optimism?'],
  'polygon.technology': ["What's Polygon?", 'Low fees?', 'Fast transactions?', 'Use Polygon?'],
  'ens.domains': ["What's ENS?", 'Decentralized usernames?', 'ENS roles?', 'Use ENS?'],
  'withtally.com': ["What's Tally?", 'Govern DAO?', 'Use Tally?', 'Tally benefits?'],
  'mirror.xyz': ["What's Mirror?", 'Publish content?', 'Use Mirror?', 'Mirror services?'],
  'sandbox.game': ["What's The Sandbox?", 'Play game?', 'Create NFTs?', 'Monetize NFTs?'],
};
